name: recsys
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - scikit-surprise=1.1.5
  - scipy
  - polars
  - implicit
  - h5py
  - lightgbm
  - catboost
  - scikit-learn
  - matplotlib
  - shap
  - mlflow
  - tqdm
